FROM python:3.10
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
COPY . .
# RUN python manage.py migrate
# RUN python manage.py collectstatic
# RUN cp -r /app/static/. /backend_static/

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "kittygram_backend.wsgi"]
#RUN python manage.py migrate
RUN python manage.py collectstatic
RUN cp -r /app/static/. /backend_static/
